# Generated by Django 3.2.8 on 2021-11-29 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('allmodels_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.allmodels')),
                ('full_name', models.CharField(max_length=500)),
                ('dob', models.DateField()),
            ],
            bases=('inventory.allmodels',),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('allmodels_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.allmodels')),
                ('title', models.CharField(max_length=500)),
                ('author_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.author')),
            ],
            bases=('inventory.allmodels',),
        ),
    ]
